version: 1.0

#Database settings for use with the influxdb3 core database. 
Influxdatabase:
  db_name: SmartGardenDatabase #Name of the database where the sensor data is stored. 
  db_host: http://192.168.0.0:8181 # IP / Hostname for the database server.  
  db_token: ${SMARTGARDEN_DATABASE} #The access token for authenticating into the database. 

#AI connection settings for Ollama api
OllamaAI:
  ai_host: http://192.168.0.0:11434
  ai_imagepath: /path/to/image/location