version: 1.2

#Database settings for use with the influxdb3 core database. 
Influxdatabase:
  #SmartGardenDatabase #Name of the database where the sensor data is stored. 
  db_name: example_database 
   # IP / Hostname for the database server. 
  db_host: http://192.168.0.0:8181
  #The access token for authenticating into the database. Use the format ${Environment_variable} 
  db_token: ${SMARTGARDEN_DATABASE}  

#AI connection settings for Ollama api
OllamaAI:
  ai_host: http://192.168.0.0:11434
  ai_imagepath: /path/to/image/location

#Pump settings -- Based on testing the below will give roughly 10ml of water
Pump:
  # Time (in seconds) for water dose
  dose_time: 2.2 
  # Pump speed for water dose
  dose_speed: 0.8
  #fine calibration settings per pump (in seconds)  
  pump1_fine_calibration: 0.4
  pump2_fine_calibration: 0.0
  pump3_fine_calibration: 0.6

#Sets the level of moisture. dry point will trigger a watering cycle, which will stop when the wet point is reached. 
Moisture:
  dry_point: 13
  wet_point: 8

#image name is the prefix name of the image, this is then followed by the date & time, the finally the file format. 
ImageSettings:
  image_name: Strawberry
  file_type: jpg
  #boolean value to compress images for storage. 1 = compress, 0 = normal file storage
  compress_image: 0 
  #24 hour representation of the time entered as a whole number value 600 = 6:00am, 1800 = 6:00pm
  image_times: [600,1200,1800] 