name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dev
      - name: Automatic requirements.txt
        uses: ryan-rozario/pipreqs-action@master
        
        with:
          PROJECT_PATH: SmartGarden   
          REQUIREMENT_PATH: SmartGarden/requirements.txt
